services:
  quick-links:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/quick_links
    profiles:
      - production

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: quick_links
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "8081:5432"
    volumes:
      - quick-links-db:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    profiles:
      - production
      - development
      - debugging

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8082:80"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    profiles:
      - production
      - development
      - debugging

  quick-links-dev:
    image: cosmtrek/air
    working_dir: /project-package
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./:/project-package/
    profiles:
      - development

  quick-links-debug:
    build:
      context: .
      dockerfile: debug/Dockerfile
    ports:
      - "8080:8080" # Application port
      - "8083:2345" # Debugging port
    depends_on:
      - db
    volumes:
      - ./debug/.air.toml:/project-package/.air.toml
      - ./:/project-package/
    profiles:
      - debugging

volumes:
  quick-links-db:
  pgadmin-data:
