services:
  quick-links:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${QUICK_LINKS_PORT}:8080
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped
    profiles:
      - production

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - quick-links-db:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    profiles:
      - production
      - development
      - debugging

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    restart: unless-stopped
    user: root
    volumes:
      - ./pgadmin/entrypoint.sh:/entrypoint_custom.sh
      - pgadmin-data:/var/lib/pgadmin
    profiles:
      - production
      - development
      - debugging
    entrypoint: /entrypoint_custom.sh

  quick-links-dev:
    image: cosmtrek/air:v1.51.0
    working_dir: /project-package
    ports:
      - ${QUICK_LINKS_PORT}:8080
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./:/project-package/
    profiles:
      - development

  quick-links-debug:
    build:
      context: .
      dockerfile: debug/Dockerfile
    ports:
      - ${QUICK_LINKS_PORT}:8080 # Application port
      - ${QUICK_LINKS_REMOTE_DEBUG_PORT}:2345 # Debugging port
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./debug/.air.toml:/project-package/.air.toml
      - ./:/project-package/
    profiles:
      - debugging

volumes:
  quick-links-db:
  pgadmin-data:
