apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-links
  labels:
    app: quick-links
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-links
  template:
    metadata:
      labels:
        app: quick-links
    spec:
      tolerations:
        - key: "workload-type"
          operator: "Equal"
          value: "untrusted"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: k3s-apps-vm
      containers:
        - name: app
          image: registry.k8s.ts.conrad-klaus.de/quick-links:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: db
          envFrom:
            - secretRef:
                name: quicklinks-postgres
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: quick-links
spec:
  type: ClusterIP
  selector:
    app: quick-links
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quick-links
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - goto.conrad-klaus.de
      secretName: goto-tls
    - hosts:
        - qr.conrad-klaus.de
      secretName: qr-tls
  rules:
    # Public access — both `goto.*` and `qr.*` aliases route to the same app
    - host: goto.conrad-klaus.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quick-links
                port:
                  number: 80
    - host: qr.conrad-klaus.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quick-links
                port:
                  number: 80
